include: [".well-known", "available"]

defaults:
  - scope:
      path: ".well-known/assetlinks.json"
    values:
      layout: none
      content_type: application/json
  - scope:
      path: "available"
    values:
      layout: none
