// Builds _data/icons.json: the SVG path data for every Font Awesome icon the site uses,
// rendered inline by _includes/icon.html. This replaces the Font Awesome CDN stylesheet
// (~100 KB of render-blocking CSS plus webfonts, loaded from Cloudflare for every visitor).
//
// Usage:
//   npm pack @fortawesome/fontawesome-free@6.7.2 && tar -xzf fortawesome-fontawesome-free-6.7.2.tgz
//   node scripts/build-icons.mjs path/to/package
//
// Run it again after adding an icon to a template, a locale file or _data/company.yml.
// Icons are referenced as:
//   templates:   {% include icon.html name="envelope" %}   {% include icon.html name="github" style="fab" %}
//   locales:     "icon": "fa-users"  (+ optional "iconStyle": "fab")
//   company.yml: social[].icon  (always brands)
//
// Font Awesome Free icons are licensed CC BY 4.0 (https://fontawesome.com/license/free);
// the attribution is kept in the generated file.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontAwesomePackageDir = process.argv[2];

if (!fontAwesomePackageDir || !fs.existsSync(path.join(fontAwesomePackageDir, "svgs"))) {
    console.error("Usage: node scripts/build-icons.mjs <path to an unpacked @fortawesome/fontawesome-free package>");
    process.exit(1);
}

const STYLE_DIRECTORIES = { fas: "solid", far: "regular", fab: "brands" };
const usedIcons = new Set(); // "style name"

const addIcon = (style, name) => usedIcons.add(`${style || "fas"} ${name.replace(/^fa-/, "")}`);

// Locale files: any object with an "icon" key.
function collectFromJson(value) {
    if (Array.isArray(value)) return value.forEach(collectFromJson);
    if (value && typeof value === "object") {
        if (typeof value.icon === "string") addIcon(value.iconStyle, value.icon);
        Object.values(value).forEach(collectFromJson);
    }
}
for (const localeFile of fs.readdirSync(path.join(rootDir, "_data", "locales"))) {
    collectFromJson(JSON.parse(fs.readFileSync(path.join(rootDir, "_data", "locales", localeFile), "utf8")));
}

// company.yml social icons (brands).
const companySource = fs.readFileSync(path.join(rootDir, "_data", "company.yml"), "utf8");
for (const [, iconName] of companySource.matchAll(/^\s+icon:\s*"?([a-z0-9-]+)"?/gm)) addIcon("fab", iconName);

// Templates: literal include calls.
const templateDirectories = ["_layouts", "_includes"];
const rootHtmlFiles = fs.readdirSync(rootDir).filter((fileName) => fileName.endsWith(".html"));
const templateFiles = [
    ...templateDirectories.flatMap((directory) =>
        fs.readdirSync(path.join(rootDir, directory)).map((fileName) => path.join(directory, fileName))),
    ...rootHtmlFiles,
];
const includePattern = /\{%-?\s*include icon\.html\s+name="([a-z0-9-]+)"(?:\s+style="(fa[srb])")?/g;
for (const templateFile of templateFiles) {
    const templateSource = fs.readFileSync(path.join(rootDir, templateFile), "utf8");
    for (const [, iconName, iconStyle] of templateSource.matchAll(includePattern)) addIcon(iconStyle, iconName);
}

// Extract viewBox + path from each SVG.
const icons = { _license: "Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com - Icons: CC BY 4.0 (https://fontawesome.com/license/free). Generated by scripts/build-icons.mjs." };
const missingIcons = [];
for (const iconKey of [...usedIcons].sort()) {
    const [style, name] = iconKey.split(" ");
    const svgPath = path.join(fontAwesomePackageDir, "svgs", STYLE_DIRECTORIES[style], `${name}.svg`);
    if (!fs.existsSync(svgPath)) {
        missingIcons.push(iconKey);
        continue;
    }
    const svgSource = fs.readFileSync(svgPath, "utf8");
    const viewBox = svgSource.match(/viewBox="([^"]+)"/)[1];
    const pathData = [...svgSource.matchAll(/<path d="([^"]+)"/g)].map(([, data]) => data).join(" ");
    icons[style] ??= {};
    icons[style][name] = { viewBox, path: pathData };
}

if (missingIcons.length) {
    console.error(`Not found in Font Awesome Free: ${missingIcons.join(", ")}`);
    process.exit(1);
}

fs.writeFileSync(path.join(rootDir, "_data", "icons.json"), `${JSON.stringify(icons, null, 2)}\n`);
console.log(`Wrote _data/icons.json with ${usedIcons.size} icons.`);
